name: Automatic Approve

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  auto-merge-cron:
    name: Automatic Merge Cron
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Merge Cron
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          BASE_BRANCHES: "main"
